import type { Locale } from "@/i18n/strings"

const en = {
  cancel: "Cancel",
  won: "Completed",
  lost: "Not completed",
  attempts: "Attempts",
  edition: "Edition",
  points: "Points",
  topPlayers: "Top of players",
  ratio: "Ratio",
  modes: "Modes",
  manual: "Manual loss",
  result: "Result",
  hints: "Hints",
  round: "Round",
  yearError: "Year error",
  years: "years",
  distance: "Distance",
  streak: "Streak",
  grid: "Result grid",
  close: "Close",
  catalog: "Design system",
}
type Copy = { [K in keyof typeof en]: string }
export const industrialCopy: Record<Locale, Copy> = {
  en,
  "pt-BR": {
    cancel: "Cancelar",
    won: "Concluído",
    lost: "Não concluído",
    attempts: "Tentativas",
    edition: "Edição",
    points: "Pontos",
    topPlayers: "Top dos jogadores",
    ratio: "Proporção",
    modes: "Modos",
    manual: "Derrota manual",
    result: "Resultado",
    hints: "Dicas",
    round: "Rodada",
    yearError: "Erro em anos",
    years: "anos",
    distance: "Distância",
    streak: "Sequência",
    grid: "Grade do resultado",
    close: "Fechar",
    catalog: "Design system",
  },
}
